# Generated by Django 5.0.1 on 2024-01-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='has_tattoo',
            field=models.CharField(choices=[('', 'any tattoo'), ('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
    ]
