# Generated by Django 5.0.1 on 2024-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hospitals_want'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='longitude',
        ),
        migrations.AddField(
            model_name='donor',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitals',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='want',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
