# Generated by Django 5.0.1 on 2024-01-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_donor_has_tattoo_alter_donor_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone_no',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
