# Generated by Django 5.0.1 on 2024-01-14 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_donor_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.districts'),
        ),
        migrations.AlterField(
            model_name='want',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.districts'),
        ),
    ]
