# Generated by Django 5.0.1 on 2024-01-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_want_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='want',
            name='hospital',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
