# Generated by Django 5.0.1 on 2024-01-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_want_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='want',
            name='hospital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
