# Generated by Django 5.0.1 on 2024-01-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_want_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='want',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
